url: "https://buendnerclub.ch" # the base hostname & protocol for your site, e.g. http://example.com
title: "Bündnerclub Zürich" # the name of your site, e.g. ACME Corp.
email: "info@buendnerclub.ch"
instagram: "https://www.instagram.com/buendnerclub_zurich/"
whatsapp: "https://chat.whatsapp.com/HtiyEf8rcflFupPtGJIq7f"
semester: "FS26"

livereload: true # automatically reloads the webview on changes
future: true # allows you to use posts with a future date

tagline: "Verein Bündner Studierende in Zürich"
description: "Offizielle Website des Bündnerclubs Zürich. Events, Mitglied werden, Über uns und mehr."

permalink: /:categories/:title/

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-email-protect

navigation:
  - title: Bündnerfest
    url: /fest/
  - title: Events
    url: /events/
  - title: Mitglied Werden
    url: /join/
  - title: Über Uns
    url: /about/

picture:
  suppress_warnings: true
  nomarkdown: false

pagination:
  enabled: true
  per_page: 10
  permalink: '/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  title: ":title (Seite :num)"
  trail:
    before: 2
    after: 2
